# Introduction to numpy

In [6]:
# importing numpy
import numpy as np
np.__version__

'1.19.2'

In [7]:
# np.<tab>
np.abs

<ufunc 'absolute'>

In [8]:
np?

### Creating an array using array() function

In [10]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Find the type of the creating array using type() function

In [13]:
type(a2)

numpy.ndarray

In [14]:
type(arr)

numpy.ndarray

### Find the dtype of the array using 'dtype' attribute

In [19]:
arr

array([1, 2, 3, 4])

In [15]:
arr.dtype

dtype('int32')

In [20]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
a2.dtype

dtype('int32')

In [37]:
af=np.array([0.2,0.3,0.4])
af

array([0.2, 0.3, 0.4])

In [38]:
af.dtype

dtype('float64')

In [39]:
ac=np.array([1+2j,3+4j])
ac

array([1.+2.j, 3.+4.j])

In [40]:
ac.dtype

dtype('complex128')

### Finding the dimension using 'ndim'

In [18]:
arr

array([1, 2, 3, 4])

In [21]:
arr.ndim

1

In [22]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
a2.ndim

2

In [25]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [26]:
a3.ndim

3

### Finding the array length using 'size'attributes

In [28]:
arr

array([1, 2, 3, 4])

In [29]:
arr.size

4

In [30]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
a2.size

10

In [32]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [33]:
a3.size

9

### Finding the shape using 'shape' attribute 

In [41]:
arr

array([1, 2, 3, 4])

In [42]:
arr.shape

(4,)

In [43]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
a2.shape

(2, 5)

In [45]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [46]:
a3.shape

(1, 3, 3)

In [47]:
ac

array([1.+2.j, 3.+4.j])

In [48]:
ac.shape

(2,)

### Finding the size of array in bytes using 'itemsize' attributes

In [49]:
arr

array([1, 2, 3, 4])

In [50]:
arr.itemsize

4

In [51]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
a2.itemsize

4

In [53]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [54]:
a3.itemsize

4

### Creating an array using array() function with dtype options

In [60]:
ad=np.array([[7,8,9,2],[1,5,3,4]],dtype=complex)
ad

array([[7.+0.j, 8.+0.j, 9.+0.j, 2.+0.j],
       [1.+0.j, 5.+0.j, 3.+0.j, 4.+0.j]])

In [61]:
ad.ndim

2

In [62]:
ad.shape

(2, 4)

In [63]:
ad.size

8

In [64]:
ad.itemsize

16

In [65]:
ad.data

### Intrinsic creation of array using 'zeros()' and 'ones()' functions

In [69]:
a_0=np.zeros((3,3),dtype=float,order='F')
a_0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
a_1=np.ones((4,5),dtype=float,order='F')
a_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
a_1=np.ones((4,5),dtype=int,order='F')
a_1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Creating an array using arange() function.
arange([start,] stop[, step,], dtype=None)
* This function generates NumPy arrays with numerical sequences that
respond to particular rules depending on the passed arguments. For example, if you want to generate a
sequence of values between 0 and 10, you will be passed only one argument to the function, that is the value
with which you want to end the sequence.

In [73]:
arange=np.arange(0,10)
arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
ar1=np.arange(0,10,2)
ar1

array([0, 2, 4, 6, 8])

In [75]:
ar2=np.arange(10,100,11)
ar2

array([10, 21, 32, 43, 54, 65, 76, 87, 98])

### Generate two dimensional array with reshape() function
arange(0,4).reshape(2,2)

In [81]:
are=np.arange(0,4)
are

array([0, 1, 2, 3])

In [83]:
are.ndim

1

In [84]:
are.shape

(4,)

In [85]:
are.size

4

In [77]:
are=np.arange(0,4).reshape(2,2)
are

array([[0, 1],
       [2, 3]])

In [78]:
are.ndim

2

In [79]:
are.shape

(2, 2)